const GLOSS=[
["Adaptive thinking","Thinking where the model decides how much to reason per request, controlled by an effort level rather than a fixed token budget. Always on for Fable 5.1; not supported on Haiku 4.5."],
["Agent","A system where the model chooses the next step at run time from available tools, rather than following a path fixed in your code."],
["Agentic loop","The cycle of send request, inspect stop_reason, execute tools, append results, repeat until end_turn."],
["Agent SDK","Anthropic's Python and TypeScript library that runs Claude Code's agent loop as a library, with built-in tools, hooks, subagents, permissions, and sessions. Formerly the Claude Code SDK. Omitting setting_sources loads user, project, and local filesystem settings by default — pass an empty array to opt out."],
["Agent teams","An experimental Claude Code shape where a lead session spawns teammates that each keep a full independent session, share a task list, and message each other directly — peer-to-peer, as against the hierarchical parent-and-subagent model. Disabled by default and interactive-only."],
["Assistant prefill","Ending a request with a partial assistant turn to force a format. Removed on Claude 4.6-and-later models: Fable 5.1, Opus 5, and Sonnet 5 reject it with a 400, and only Haiku 4.5 still accepts it. output_config.format is the replacement."],
["Bash sandbox","Claude Code's built-in OS-enforced isolation for shell commands — Seatbelt on macOS, namespaces on Linux and WSL2 — configured with filesystem allow and deny rules and network egress rules rather than provisioned as separate infrastructure."],
["Auto memory","Notes Claude Code writes for itself per repository. The MEMORY.md index loads at session start; topic files load on demand."],
["Batch API","Asynchronous processing of many requests within a 24-hour window at 50% off input and output. Stacks with prompt caching."],
["CLAUDE.md","A Markdown file of standing instructions for Claude Code. Delivered as a user message after the system prompt — context, not enforcement. Files concatenate across scopes."],
["cache_control","The field marking a cacheable prefix, either once at the top level for automatic caching or on specific content blocks. Maximum four explicit breakpoints per request."],
["Compaction","Summarising the conversation so far and continuing from the summary. Lossy by design."],
["Content block","The unit of a Messages request or response: text, tool_use, tool_result, thinking, image, document, server_tool_use."],
["Context engineering","Curating what occupies the context window over a long session, as distinct from writing a single prompt well."],
["Context window","The total token budget for system prompt, tools, history, documents, thinking, and the response. 1M on current top models; 200K on Haiku 4.5."],
["Effort level","A setting controlling how much the model reasons, from low through high, with xhigh and max on some models."],
["Few-shot / multi-shot","Supplying several worked examples in the prompt. The most reliable technique for output consistency."],
["Hook","Code that Claude Code runs automatically at a lifecycle event. Exit code 2 blocks on events that can block; exit 1 does not."],
["Indirect prompt injection","Malicious instructions planted in content the agent retrieves — a web page, document, email, or tool result — rather than typed by the user."],
["MCP","Model Context Protocol. An open protocol in which a host runs one client per server; servers expose tools, resources, and prompts over stdio, HTTP (streamable HTTP), or in-process. Plain SSE is the deprecated predecessor of the HTTP transport."],
["Managed Agents","Anthropic-hosted agent infrastructure with stateful sessions and persistent event history, billed on tokens plus session runtime."],
["Managed settings","Organisation-deployed configuration that sits above every other settings scope and cannot be overridden from below, except where a stricter value is honoured."],
["Orchestrator–workers","A pattern where a lead model decomposes the task at run time and dispatches to workers. The run-time decomposition is what makes it agentic."],
["output_config.format","A Messages API parameter carrying a JSON Schema that the model's own response is grammar-constrained to match. Client SDK helpers taking a Zod or Pydantic model wrap this same parameter. Single-turn only; see Structured outputs for the multi-turn case."],
["Permission mode","How much Claude Code asks before acting: default, plan, acceptEdits, auto, dontAsk, bypassPermissions. Deny rules win in every mode."],
["Plugin","An installable bundle of commands, skills, subagents, hooks, and MCP servers, distributed through a marketplace with pinnable versions."],
["Prompt caching","Reusing a processed prompt prefix across requests. Lookup runs tools, then system, then messages; reads cost 0.1x base input, or 0.025x on Fable 5.1 and Mythos 5.1. The minimum cacheable prefix is per-model: 512 tokens on Fable 5.1 and Opus 5, 1,024 on Sonnet 5, 4,096 on Haiku 4.5."],
["Rules","Topic files in .claude/rules/. With paths: frontmatter they load only when Claude touches matching files."],
["Server-side tool","A tool that runs on Anthropic's infrastructure inside the turn, such as web search or code execution. Reported in usage.server_tool_use."],
["Skill","A folder with SKILL.md whose description makes it discoverable. Teaches a procedure and loads on demand, so it costs almost no context until used."],
["stop_reason","The authoritative signal for what happens next: end_turn, tool_use, max_tokens, stop_sequence, pause_turn, refusal, model_context_window_exceeded."],
["Structured outputs","Returning validated typed data by supplying a schema rather than asking for JSON in prose. Two mechanisms: output_config.format constrains a single Messages API response, while the Agent SDK's output_format option validates the final result of a whole multi-turn session, tools included."],
["Subagent","A nested agent with its own context window, system prompt, and tool set. Communicates with its parent by summary only."],
["temperature","A sampling parameter, deprecated on every model released after Claude Opus 4.6 — which includes Fable 5.1, Opus 5, Sonnet 5, and Haiku 4.5. These accept only the default 1.0 and reject any other value with a 400. top_p and top_k are deprecated the same way."],
["Tool search","Loading tool definitions on demand rather than registering all of them, for agents with very large tool sets."],
["tool_choice","Controls tool selection: auto, any, a named tool, or none. Fable 5.1 supports only auto and none — forcing a specific or any tool returns a 400 there."],
["Workflow","A system where the sequence of model calls is fixed in your code. Deterministic, testable, and cheaper than an agent."]
];

/* ============ QUICK REFERENCE ============ */
const REF=[
["stop_reason values",[
["end_turn","Finished naturally — return the result"],
["tool_use","Execute tools, append results, call again"],
["max_tokens","Output truncated at your ceiling — do not parse as complete"],
["stop_sequence","A stop string was generated"],
["pause_turn","Long-running server tool turn paused — send it back to continue"],
["refusal","Claude declined, on a 200 response"],
["model_context_window_exceeded","Generation filled the window — reduce input or compact"]]],
["HTTP errors and retryability",[
["400 invalid_request_error","Fix the request. Do not retry"],
["401 authentication_error","Key problem. Do not retry"],
["402 billing_error","Billing problem. Do not retry"],
["403 permission_error","Key lacks access. Do not retry"],
["404 not_found_error","Wrong endpoint. Do not retry"],
["409 conflict_error","Concurrent modification, or a uniqueness collision. Resolve the conflict first, then retry"],
["413 request_too_large","Shrink the request. Do not retry. 32 MB Messages, 256 MB Batch, 500 MB Files"],
["429 rate_limit_error","Your usage against your limit — back off. A spend-cap 429 has no retry-after and keeps failing until the cap resets"],
["500 api_error","Anthropic internal — retry with backoff"],
["504 timeout_error","Retry, and stream long generations"],
["529 overloaded_error","Server capacity, not your quota — back off"]]],
["Model lineup",[
["Fable 5.1","1M ctx, 128K out, adaptive always on (cannot be disabled), $10/$50. No forced tool_choice. 512-token cache floor"],
["Opus 5","1M ctx, 128K out, adaptive, $5/$25. Fast mode available. 512-token cache floor"],
["Sonnet 5","1M ctx, 128K out, adaptive, $2/$10. 1,024-token cache floor"],
["Haiku 4.5","200K ctx, 64K out, extended thinking, no effort param, $1/$5. 4,096-token cache floor — the highest. The only one that still accepts prefill"],
["All four","No settable temperature / top_p / top_k. Full 1M window bills at one flat rate"]]],
["Deprecated or removed on this generation",[
["temperature, top_p, top_k","Deprecated after Opus 4.6 — all four current models accept only the default and 400 on anything else"],
["Assistant prefill","400 on Fable 5.1, Opus 5, Sonnet 5. Haiku 4.5 still accepts it. Use output_config.format"],
["Extended thinking","Removed on 4.7-and-later — adaptive thinking plus effort replaces it. Haiku 4.5 is still extended-only"],
["Forced tool_choice","Not supported on Fable 5.1 (any / named tool both 400). auto and none are fine"],
["MCP plain SSE transport","Deprecated in favour of HTTP (streamable HTTP); fallback only"],
["Claude Code SDK (name)","Renamed the Claude Agent SDK — same product"]]],
["Cost multipliers",[
["5-minute cache write","1.25x base input — breaks even after 1 read"],
["1-hour cache write","2x base input — breaks even after 2 reads"],
["Cache read","0.1x base input (0.025x on Fable 5.1 / Mythos 5.1)"],
["Batch API","50% off input and output; stacks with caching"],
["Data residency","1.1x on every token category when inference_geo pins one country. Claude 4.6+ only"],
["Output tokens","5x input on every tier — brevity is the cheapest lever"],
["Min cacheable prefix","512 Fable 5.1 / Opus 5, 1,024 Sonnet 5, 4,096 Haiku 4.5; below it nothing caches, silently"],
["4.7-generation tokeniser","~30% more tokens for the same text than Sonnet 4.6 and earlier — re-measure after migrating"]]],
["settings.json precedence",[
["1 Managed","managed-settings.json, MDM, console"],
["2 Command line","claude --settings, one session"],
["3 Project local",".claude/settings.local.json — gitignored"],
["4 Shared project",".claude/settings.json — committed"],
["5 User","~/.claude/settings.json"],
["Note","Scalars override; list keys such as permissions.allow merge"]]],
["CLAUDE.md scopes (concatenated, not overridden)",[
["Managed policy","/etc/claude-code/CLAUDE.md and platform equivalents — cannot be excluded"],
["User","~/.claude/CLAUDE.md"],
["Project","./CLAUDE.md or ./.claude/CLAUDE.md"],
["Local","./CLAUDE.local.md — gitignore it"],
["Rules",".claude/rules/*.md; paths: frontmatter defers loading"]]],
["Hook exit codes",[
["0","Success, no decision — stdout may carry JSON for structured control"],
["2","Blocking error on events that can block; stderr is the reason"],
["1 or any other","Non-blocking error — the action proceeds"],
["PermissionRequest","The exception: exit 2 is not honoured. Deny through the decision object instead"],
["Timeout on PreToolUse","Does not block a command, http, or mcp_tool hook. An Agent SDK callback hook does block on timeout"]]],
["Choosing an extension",[
["Built-in tool","Claude already has the capability"],
["Skill","Knowledge or procedure, loaded on demand"],
["MCP server","New capability, reused across applications"],
["Custom tool","New capability for one application"],
["Hook / permission rule","Must happen deterministically, every time"]]],
["Workflow patterns",[
["Prompt chaining","Fixed sequential stages"],
["Routing","Classify, then send to a specialised path"],
["Parallelisation","Sectioning (split work) or voting (repeat work)"],
["Orchestrator–workers","Lead model decomposes at run time"],
["Evaluator–optimiser","Produce, critique, iterate until it passes"]]],
["Diagnostic commands",[
["/status","Which settings sources loaded"],
["/context","Which instruction files are in context"],
["/hooks","Configured hooks and their source"],
["/mcp","MCP server connections"],
["claude doctor","Entries Claude Code rejected"]]]
];
